### ISSUE TITLE
Unable to select Specialisation after clicking "apply"

### ISSUE THREAD

**Issue by TaitKaito** [SpaceAIDS/SAIDSModRepository#15]
**Description:**
You cannot select your specialisation after clicking the apply within the shipcores mod, 

**Steps to reproduce:**
Place ship core, select bonus, dont select specialisation, click the apply

**Expected behavior:**
I'd expect to be able to change between specialisations for things like refitting a ship without needing to completely break the block to fix, as well as choose damage reduction mod but no specialisation if a ship isnt meant to have one but still have PD

**Where did the issue occur?**
Public Server on SAIDS

**Log Files:**
- SpaceEngineers-[numbers].log found in %Appdata%/SpaceEngineers

**Additional context:**
Also point defence options are seemingly limited to specialisation system so an artillery ship cant have any energy PD nor could it have any gatling pd

**Screenshots:**
![image](https://github.com/SpaceAIDS/SAIDSModRepository/assets/29630172/f3604d16-6335-469c-afc0-3ec7e26ffd8a)

**Comment by InvalidArgument3** [comment]
i think this was fixed, just had to grind a place a new one. make sure to spend all your points before hitting apply
